### ISSUE TITLE
Compilation fails with the Intel C++ compiler

### ISSUE THREAD

**Issue by mgduda** [jerahmie/grid_filter#8]
With the Intel C++ compiler (version 19.1.1), compilation fails for the `grid_filter.cpp` file with the following error message:
```
[  8%] Building CXX object src/CMakeFiles/filter_obs.dir/grid_filter.cpp.o
/glade/u/home/duda/jerahmie/grid_filter/src/grid_filter.cpp(60): error: namespace "std" has no member "reduce"
    long mask_sum = std::reduce(obs_mask.begin(), obs_mask.end());
                         ^
```
To reproduce this issue on Cheyenne, the following modules can be used:
```
Currently Loaded Modules:
  1) ncarenv/1.3   2) intel/19.1.1   3) ncarcompilers/0.5.0   4) mpt/2.25   5) netcdf/4.8.1   6) cmake/3.18.2
```

**Comment by jerahmie** [comment]
Obs filter now builds with Intel compiler.  

Unittests are not currently compiled for Intel compiler.  Catch2 won't build with Intel C++ compiler because system the system gcc-toolchain doesn't support modern C++ features.  [https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/gcc-compatibility-and-interoperability.html](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/gcc-compatibility-and-interoperability.html
)
Loading more modern GCC through software modules conflicts with Intel compilers.
[cmake_intel.log](https://github.com/jerahmie/grid_filter/files/12539760/cmake_intel.log)
[make_intel.log](https://github.com/jerahmie/grid_filter/files/12539757/make_intel.log)
